version: '3'

services:
        db:
                image: mariadb
                environment:
                        - MYSQL_ROOT_PASSWORD=Qoswlfdlsnrn
                        - MYSQL_DATABASE=jaram
                        - MYSQL_USER=jaram
                        - MYSQL_PASSWORD=Qoswlfdlsnrn
        web:
                build: .
                command: python3 manage.py runserver 0.0.0.0:8000
                volumes:
                        - .:/code
                ports:
                                                      - "8000:8000"
                depends_on:
                        - db
